apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-batch
  labels:
    app: cpu-batch
  annotations:
    slo.hybrid.io/class: "batch"
    slo.hybrid.io/deadlineMs: "100000"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: cpu-batch
        scheduling.hybrid.io/managed: "true"
      annotations:
        slo.hybrid.io/class: "batch"
        slo.hybrid.io/deadlineMs: "100000"
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: wdhif/stress-ng:latest
          env:
            - name: CPU_WKRS
              value: "2"
            - name: CPU_LOAD
              value: "95"
            - name: CPU_SEC
              value: "90"
          args:
            - --cpu
            - "$(CPU_WKRS)"
            - --cpu-load
            - "$(CPU_LOAD)"
            - --timeout
            - "$(CPU_SEC)s"
            - --metrics-brief
          resources:
            requests: { cpu: "1500m", memory: "256Mi" }
            limits:   { cpu: "2",      memory: "512Mi" }