apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-batch
  labels: { app: cpu-batch }
  annotations:
    slo.hybrid.io/class: "batch"
    slo.deadline.ms: "100000"
    slo.hybrid.io/max-offload-penalty.ms: "500"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels: { app: cpu-batch }
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: wdhif/stress-ng:latest  # pin a specific tag for reproducibility
          env:
            - name: CPU_WKRS
              value: "2"
            - name: CPU_LOAD
              value: "95"
            - name: CPU_SEC
              value: "90"
          # The image entrypoint is `stress-ng`, so we only pass args:
          args:
            - --cpu
            - "$(CPU_WKRS)"
            - --cpu-load
            - "$(CPU_LOAD)"
            - --timeout
            - "$(CPU_SEC)s"
            - --metrics-brief
          resources:
            requests: { cpu: "1500m", memory: "256Mi" }
            limits:   { cpu: "2",      memory: "512Mi" }