apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-latency
  labels:
    app: http-latency
  annotations:
    slo.hybrid.io/class: "latency"
    slo.hybrid.io/latencyTargetMs: "100"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-latency
  template:
    metadata:
      labels:
        app: http-latency
        scheduling.hybrid.io/managed: "true"
      annotations:
        slo.hybrid.io/class: "latency"
        slo.hybrid.io/latencyTargetMs: "100"
    spec:
      containers:
        - name: nginx
          image: openresty/openresty:1.21.4.1-0-alpine
          ports:
            - containerPort: 80
          env:
            - name: CPU_SPIN_ITERS
              value: "50000"
          volumeMounts:
            - name: nginx-conf
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 1
          resources:
            requests:
              cpu: "300m"
              memory: "160Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: nginx-conf
          configMap:
            name: http-latency-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: http-latency
  labels:
    app: http-latency
spec:
  selector:
    app: http-latency
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP