apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: smart-scheduler-webhook
webhooks:
  - name: 00-mutate-pods.scheduling.hybrid.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    timeoutSeconds: 5
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    objectSelector:
      matchLabels:
        scheduling.hybrid.io/managed: "true"
    clientConfig:
      service:
        name: smart-scheduler-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutate
        port: 443
      caBundle: ""